### ISSUE TITLE
typedef isn't currently supported

### ISSUE THREAD

**Issue by mrinterweb** [evanphx/stark#6]
With the following example Thrift file:

``` Thrift
namespace rb Foo

struct Bar {
  1: string name
}

typedef list<Bar> Bars
```

Thrift processes this file without error, but when I process the same file with stark, I get the following error.

``` text
D, [2013-04-10T14:43:08.935611 #13386] DEBUG -- : Materializing a.thrift
/home/sean/.rvm/gems/ruby-1.9.3-p374/gems/stark-0.7.0/lib/stark/raw_parser.rb:117:in `raise_error': @7:17 failed rule 'identifier', got '>' (Stark::Parser::ParseError)
    from /home/sean/.rvm/gems/ruby-1.9.3-p374/gems/stark-0.7.0/lib/stark/parser.rb:24:in `ast'
    from /home/sean/.rvm/gems/ruby-1.9.3-p374/gems/stark-0.7.0/lib/stark/parser.rb:30:in `ast'
    from /home/sean/.rvm/gems/ruby-1.9.3-p374/gems/stark-0.7.0/lib/stark.rb:21:in `materialize'
    from /home/sean/work/cc_thrift/lib/cc_thrift/base.rb:24:in `block in materialize_all_thrift_files!'
    from /home/sean/work/cc_thrift/lib/cc_thrift/base.rb:22:in `each'
    from /home/sean/work/cc_thrift/lib/cc_thrift/base.rb:22:in `materialize_all_thrift_files!'
    from test.rb:2:in `<main>'
```

**Comment by mrinterweb** [comment]
I no longer work with the codebase that experienced this issue. Closing as I will not be able to verify a fix.
